$: << File.join(File.dirname(__FILE__), "/lib")
require 'boleto_api'

# Serves the interactive API documentation (Scalar) from the static files
# in docs/ (openapi.json is generated by scripts/generate_openapi.rb).
# Mounted at /docs so Scalar's "Try it" hits the same origin as the API.
class DocsApp
  DOCS_ROOT = File.join(__dir__, 'docs')
  FILES = {
    '' => ['index.html', 'text/html; charset=utf-8'],
    '/' => ['index.html', 'text/html; charset=utf-8'],
    '/index.html' => ['index.html', 'text/html; charset=utf-8'],
    '/openapi.json' => ['openapi.json', 'application/json']
  }.freeze

  def self.call(env)
    file = FILES[env['PATH_INFO']]
    return [404, { 'content-type' => 'text/plain' }, ["not found\n"]] unless file

    body = File.binread(File.join(DOCS_ROOT, file[0]))
    [200, { 'content-type' => file[1], 'content-length' => body.bytesize.to_s }, [body]]
  end
end

app = Rack::Builder.new do
  map '/docs' do
    run DocsApp
  end
  map '/' do
    run BoletoApi::Server
  end
end

run app
